#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


class DashboardStaticTests(unittest.TestCase):
    def test_room_chat_renders_generation_intent_and_stale_state(self):
        js = (ROOT / "시스템/대시보드/웹/js/room-chat.js").read_text(encoding="utf-8")
        self.assertIn("gen #", js)
        self.assertIn("runningIntent", js)
        self.assertIn("publishLedger", js)
        self.assertIn("contextPacks", js)
        self.assertIn("learning", js)
        self.assertIn("pub ${committed} done", js)
        self.assertIn("pack ${count}", js)
        self.assertIn("latest_lesson_pack_status", js)
        self.assertIn("lesson ${contextPacks.latest_lesson_pack_status}", js)
        self.assertIn("tasks.task_count", js)
        self.assertIn("tasks ${count}", js)
        self.assertIn("releaseQueue.release_count", js)
        self.assertIn("release ${count}", js)
        self.assertIn("approval", js)
        self.assertIn("pending_items", js)
        self.assertIn("approved_items", js)
        self.assertIn("data-release-action", js)
        self.assertIn("approveRelease", js)
        self.assertIn("rejectRelease", js)
        self.assertIn("publishRelease", js)
        self.assertIn("cancelTask", js)
        self.assertIn("data-task-action", js)
        self.assertIn("cancel_requested", js)
        self.assertIn("running_items", js)
        self.assertIn("heartbeat_phase", js)
        self.assertIn("renderStatusDetails", js)
        self.assertIn("room-status-detail", js)
        self.assertIn("renderTaskPanel", js)
        self.assertIn("room-task-panel", js)
        self.assertIn("taskPanelHasRows", js)
        self.assertIn("taskStateKind", js)
        self.assertIn("heartbeat_age_ms", js)
        self.assertIn("heartbeat_stale", js)
        self.assertIn("heartbeat_stale_threshold_ms", js)
        self.assertIn("stale_task_count", js)
        self.assertIn("progress_report_due_count", js)
        self.assertIn("progress_report_requested_count", js)
        self.assertIn("progress_report_due", js)
        self.assertIn("progress_report_requested_since_heartbeat", js)
        self.assertIn("latest_steering_reason_code", js)
        self.assertIn("report due", js)
        self.assertIn("steeringAckPending", js)
        self.assertIn("steering_runtime_state", js)
        self.assertIn("steering_runtime_label", js)
        self.assertIn("steering_runtime_count", js)
        self.assertIn("task_runtime_activity", js)
        self.assertIn("runtime_activity_items", js)
        self.assertIn("taskRuntimeActivity", js)
        self.assertIn("task-runtime", js)
        self.assertIn("steer ${item.steering_action}", js)
        self.assertIn("revise_restarting", js)
        self.assertIn("taskAttentionScore", js)
        self.assertIn("pending_steering_ack", js)
        self.assertIn("progressTask", js)
        self.assertIn("reviseTask", js)
        self.assertIn("updateTaskWorkSettings", js)
        self.assertIn("openWorkSettingsModal", js)
        self.assertIn("openTaskControlModal", js)
        self.assertIn("task-control-modal", js)
        self.assertIn("latest_steering_requested_at", js)
        self.assertIn("latest_steering_control_request_source_event_seq", js)
        self.assertIn("pending_ack_steering_action", js)
        self.assertIn("pending_ack_steering_instruction", js)
        self.assertIn("progress_report_due_reason", js)
        self.assertIn("최근 요청:", js)
        self.assertIn("ack 대기:", js)
        self.assertIn("task-action", js)
        self.assertNotIn('prompt("작업 취소 사유"', js)
        self.assertNotIn('prompt("부분 보고 요청"', js)
        self.assertNotIn('prompt("작업 재지시"', js)
        label_body = re.search(r"function taskStateLabel\(item = \{\}\) \{(?P<body>.*?)\n\}", js, re.S).group("body")
        kind_body = re.search(r"function taskStateKind\(item = \{\}\) \{(?P<body>.*?)\n\}", js, re.S).group("body")
        score_body = re.search(r"function taskAttentionScore\(item = \{\}\) \{(?P<body>.*?)\n\}", js, re.S).group("body")
        self.assertLess(label_body.index("cancel_requested"), label_body.index("heartbeat_stale"))
        self.assertLess(kind_body.index("cancel_requested"), kind_body.index("heartbeat_stale"))
        self.assertLess(score_body.index("cancel_requested"), score_body.index("heartbeat_stale"))
        self.assertIn("projection_lag_by_member", js)
        self.assertIn("projection_baseline_event_seq", js)
        self.assertIn("baseline #${m.projection_baseline_event_seq}", js)
        self.assertIn("seat_projection_baselines", js)
        self.assertIn("seat_projection_baseline_count", js)
        self.assertIn("late join ${count}", js)
        self.assertIn("projection lag ${m.tail_lag || 0}", js)
        self.assertIn("projection_required_event_count", js)
        self.assertIn("recovery_actions", js)
        self.assertIn("상태 지연 ·", js)
        self.assertIn("learn ${lessons} lessons", js)
        self.assertIn("promotion_pending_count", js)
        self.assertIn("promotion_candidate_pending_count", js)
        self.assertIn("promotion_candidate_target_counts", js)
        self.assertIn("growth_gap_open_count", js)
        self.assertIn("growth_gap_state_counts", js)
        self.assertIn("성장 갭", js)
        self.assertIn("gaps", js)
        self.assertIn("renderPromotionReviewPanel", js)
        self.assertIn("room-promotion-review", js)
        self.assertIn("wireObserverControls", js)
        self.assertIn("applyObserverVisibility", js)
        self.assertIn("defaultObserverCollapsed", js)
        self.assertIn('window.matchMedia("(min-width: 721px)").matches', js)
        self.assertIn("room-observer-all-toggle", js)
        self.assertIn("data-observer-section", js)
        self.assertIn("OBSERVER_COLLAPSE_STORAGE_KEY", js)
        self.assertIn("OBSERVER_SECTIONS_STORAGE_KEY", js)
        self.assertIn("data-section-hidden", js)
        self.assertIn("promotionReviewPanelHasRows", js)
        self.assertIn("promotionReviewStateLabel", js)
        self.assertIn("promotionReviewSortKey", js)
        self.assertIn("data-promotion-action", js)
        self.assertIn("scanLessonPromotions", js)
        self.assertIn("approveLessonPromotion", js)
        self.assertIn("rejectLessonPromotion", js)
        self.assertIn("applyLessonPromotion", js)
        self.assertIn("promotionApplyStateLabel", js)
        self.assertIn("promotion_apply_pending_count", js)
        self.assertIn("resource_apply_applied_count", js)
        self.assertIn("적용대기", js)
        self.assertIn("적용완료", js)
        self.assertIn("적용차단", js)
        self.assertIn('data-promotion-action="apply"', js)
        self.assertIn("성장 후보", js)
        self.assertIn("레슨 보고 누락", js)
        self.assertIn("pending", js)
        self.assertIn("status stale", js)
        self.assertIn("상태 지연", js)
        self.assertIn("stale wake", js)
        self.assertIn("renderCandidatePanel", js)
        self.assertIn("room-candidate-panel", js)
        self.assertIn("state_counts", js)
        self.assertIn("selected_published", js)
        self.assertIn("synthesized_published", js)
        self.assertIn("superseded", js)
        self.assertIn("candidateStateLabel", js)
        self.assertIn("candidateSortKey", js)
        self.assertIn("transitioned_at || item.created_at", js)
        self.assertIn("candidatePanelHasRows", js)
        self.assertIn("renderTurnHandoffPanel", js)
        self.assertIn("room-turn-handoff", js)
        self.assertIn("latest_turn_handoff", js)
        self.assertIn("latest_turn_handoff_id", js)
        self.assertIn("turn_handoff_brief_preview", js)
        self.assertIn("manager_message_preview", js)
        self.assertIn("response_target", js)
        self.assertIn("return_contract", js)
        self.assertIn("request_work_route", js)
        self.assertIn('chips.push(["handoff"', js)
        self.assertIn("renderObligationPanel", js)
        self.assertIn("room-obligation-panel", js)
        self.assertIn("response_obligations", js)
        self.assertIn("obligationStateLabel", js)
        self.assertIn("reply ${count}", js)
        self.assertIn("overdue_open_count", js)
        self.assertIn("auto_policy", js)
        self.assertIn("policy_blockers", js)
        self.assertIn("overdue", js)
        self.assertIn('["obligation", "room-obligation-panel"]', js)
        self.assertIn("space_memory", js)
        self.assertIn("projection_available", js)
        self.assertIn("latest_memory_projection_id", js)
        self.assertIn("memory #${seq", js)
        self.assertIn("맥락 projection", js)
        self.assertIn("user_directive_items", js)
        self.assertIn("active_topic_threads", js)
        self.assertIn("dormant_topic_threads", js)
        self.assertRegex(
            js,
            r"renderChatFlowPanel\(st\);\s*renderObligationPanel\(st\);\s*renderTurnHandoffPanel\(st\);\s*renderTaskPanel\(st\);\s*renderCandidatePanel\(st\);\s*renderPromotionReviewPanel\(st\);",
        )

    def test_work_settings_edit_entrypoints_are_wired(self):
        api_js = (ROOT / "시스템/대시보드/웹/js/api.js").read_text(encoding="utf-8")
        people_js = (ROOT / "시스템/대시보드/웹/js/people.js").read_text(encoding="utf-8")
        spaces_js = (ROOT / "시스템/대시보드/웹/js/spaces.js").read_text(encoding="utf-8")
        room_js = (ROOT / "시스템/대시보드/웹/js/room-chat.js").read_text(encoding="utf-8")

        self.assertIn("updatePersonWorkSettings", api_js)
        self.assertIn("updateSpaceWorkSettings", api_js)
        self.assertIn("updateSeatWorkSettings", api_js)
        self.assertIn("updateTaskWorkSettings", api_js)
        self.assertIn("/work-settings", api_js)
        self.assertIn("/members/${encodeURIComponent(person)}/work-settings", api_js)
        self.assertIn("/tasks/${encodeURIComponent(taskId)}/work-settings", api_js)
        self.assertIn("/activity?limit=", api_js)
        self.assertIn('json("PATCH", { actor, ...settings })', api_js)
        self.assertIn("person-work-settings-btn", people_js)
        self.assertIn("space-work-settings-btn", spaces_js)
        self.assertIn("seat-work-settings-btn", spaces_js)
        self.assertIn("seatWorkSettingsPanel", spaces_js)
        self.assertIn("api.updateSeatWorkSettings", spaces_js)
        self.assertIn("data-configured-keys", spaces_js)
        self.assertIn("{ partial: true }", spaces_js)
        self.assertIn("seat-settings-panel", spaces_js)
        self.assertIn("seat-settings-count", spaces_js)
        self.assertIn("직접 ${configuredCount}", spaces_js)
        self.assertIn("작업 실행설정 수정", people_js)
        self.assertIn("작업 실행설정 수정", spaces_js)
        self.assertIn("openWorkSettingsModal", people_js)
        self.assertIn("configured_keys", people_js)
        self.assertIn("edit-runner-timeout-override", people_js)
        self.assertIn("체크한 항목만", people_js)
        self.assertIn("datasetKey: \"runnerTimeoutSec\"", people_js)
        self.assertIn("input.value = settings[field.datasetKey] || settings[field.key] || field.fallback", people_js)
        self.assertIn("values[field.key] = Number(document.getElementById(field.input).value", people_js)
        self.assertIn("selected.push(field.key)", people_js)
        self.assertIn("data-task-action=\"settings\"", room_js)
        self.assertIn("현재 실행 중인 작업에도 반영", room_js)
        self.assertIn("button?.dataset || {}", room_js)
        self.assertIn("api.spaceActivity", room_js)
        self.assertIn("activityFilterOptions", room_js)
        self.assertIn("data-activity-filter", room_js)
        self.assertIn("renderChatFlowPanel", room_js)
        self.assertIn("room-chat-flow", room_js)
        self.assertIn("chat_flow", room_js)
        self.assertIn('["manager", "공간관리", counts.manager]', room_js)
        self.assertIn("transientStatusBubble", room_js)
        self.assertIn("latestRoomStatus", room_js)
        self.assertIn("MESSAGE_REFRESH_MS = 1500", room_js)
        self.assertIn("STATUS_REFRESH_MS = 1500", room_js)
        self.assertIn("턴을 받아 생각 중", room_js)
        self.assertIn("응답 중", room_js)
        self.assertIn('state.includes("work_settings")', room_js)
        self.assertIn('state.includes("timeout")', room_js)
        self.assertIn('label.includes("시간 초과")', room_js)
        self.assertIn("ACTIVITY_FULL_REFRESH_MS", room_js)
        self.assertIn("mergeActivityRows", room_js)
        self.assertIn("forceActivity", room_js)
        index = (ROOT / "시스템/대시보드/웹/index.html").read_text(encoding="utf-8")
        self.assertNotIn("<label class=\"work-override-row\"", index)
        self.assertIn("<div class=\"work-override-row\" hidden>", index)
        self.assertIn('id="room-observer-stack"', index)
        self.assertIn('id="room-diagnostics-toolbar"', index)
        self.assertIn('id="room-observer-all-toggle"', index)
        self.assertIn('id="people-panel"', index)
        self.assertIn('id="spaces-panel"', index)
        self.assertIn('id="chat-panel"', index)
        self.assertIn('data-layout-panel="agents"', index)
        self.assertIn('data-layout-panel="spaces"', index)
        self.assertIn('data-layout-panel="chat"', index)
        self.assertIn('data-layout-panel="viewer"', index)
        self.assertIn('class="workspace-splitter"', index)
        self.assertIn('data-splitter-left="agents"', index)
        self.assertIn('data-splitter-right="spaces"', index)
        self.assertIn('data-splitter-left="spaces"', index)
        self.assertIn('data-splitter-right="chat"', index)
        self.assertIn('data-splitter-left="chat"', index)
        self.assertIn('data-splitter-right="viewer"', index)
        self.assertIn('role="separator"', index)
        self.assertIn('aria-orientation="vertical"', index)
        self.assertNotIn('id="toggle-sidebar"', index)
        self.assertNotIn('data-view="roomView"', index)
        self.assertIn('aria-controls="room-snapshot room-observer-stack"', index)
        self.assertIn('aria-expanded", observerCollapsed ? "false" : "true"', room_js)
        self.assertIn('data-observer-section="snapshot"', index)
        self.assertIn('data-observer-section="activity"', index)
        self.assertIn('data-observer-section="obligation"', index)
        self.assertIn('aria-controls="room-promotion-review"', index)
        self.assertIn('id="room-chat-flow"', index)
        self.assertIn('id="room-obligation-panel"', index)
        self.assertIn('id="room-turn-handoff"', index)
        self.assertIn('id="room-sub"', index)
        self.assertIn('id="room-participants"', index)
        self.assertIn('id="room-space-select"', index)
        self.assertIn('id="room-latest"', index)
        self.assertIn('id="task-control-modal"', index)
        self.assertIn('id="task-control-input"', index)
        self.assertIn('id="person-picker-modal"', index)
        self.assertIn('id="person-picker-select"', index)
        self.assertIn('id="room-member-form"', index)
        self.assertIn('id="room-member-select"', index)
        self.assertIn('id="files-splitter"', index)
        self.assertIn('aria-orientation="horizontal"', index)
        self.assertIn('id="room-promotion-review"', index)

    def test_room_chat_input_cannot_disable_space_manager(self):
        index = (ROOT / "시스템/대시보드/웹/index.html").read_text(encoding="utf-8")
        room_js = (ROOT / "시스템/대시보드/웹/js/room-chat.js").read_text(encoding="utf-8")
        css = (ROOT / "시스템/대시보드/웹/css/style.css").read_text(encoding="utf-8")

        self.assertNotIn("room-run-manager", index + room_js)
        self.assertNotIn("공간관리 실행", index)
        self.assertNotIn("room-manager-toggle", index + room_js + css)
        self.assertIn("room-manager-lock", index)
        self.assertIn("공간관리 항상 실행", index)
        self.assertIn('api.postSpace(item.space, item.text, "대표", true, item.clientMessageId)', room_js)

    def test_viewer_skill_tab_exposes_skill_description_and_source(self):
        index = (ROOT / "시스템/대시보드/웹/index.html").read_text(encoding="utf-8")
        api_js = (ROOT / "시스템/대시보드/웹/js/api.js").read_text(encoding="utf-8")
        cases_js = (ROOT / "시스템/대시보드/웹/js/cases.js").read_text(encoding="utf-8")
        css = (ROOT / "시스템/대시보드/웹/css/style.css").read_text(encoding="utf-8")

        self.assertIn('data-view="casesView">스킬</button>', index)
        self.assertIn("스킬 설명과 SKILL.md", index)
        self.assertIn("skillDetail", api_js)
        self.assertIn("api.skillDetail(skill)", cases_js)
        self.assertIn("frontmatter description", cases_js)
        self.assertIn("SKILL.md 보기", cases_js)
        self.assertIn("skill-summary", css)
        self.assertIn("skill-source-code", css)

    def test_room_chat_rapid_outbox_and_backlog_contract_is_visible(self):
        room_js = (ROOT / "시스템/대시보드/웹/js/room-chat.js").read_text(encoding="utf-8")
        css = (ROOT / "시스템/대시보드/웹/css/style.css").read_text(encoding="utf-8")

        self.assertIn("let outbox = []", room_js)
        self.assertIn("outboxProcessing", room_js)
        self.assertIn("processOutboxQueue", room_js)
        self.assertIn("outboxStateLabel", room_js)
        self.assertIn("markRecordedOutbox", room_js)
        self.assertIn("전송 대기", room_js)
        self.assertIn("전송 중", room_js)
        self.assertIn("전송 실패", room_js)
        self.assertIn("item.state = \"acked\"", room_js)
        self.assertIn("await refreshAfterPost(item.space)", room_js)
        self.assertIn("console.warn(\"표시 갱신 실패\"", room_js)
        self.assertIn("console.warn(\"전체 목록 갱신 실패\"", room_js)
        self.assertIn("serverClientIds.has(item.clientMessageId)", room_js)
        self.assertIn("isRoomMessagesNearBottom", room_js)
        self.assertIn("updateLatestButton", room_js)
        self.assertIn("scrollRoomToLatest", room_js)
        self.assertIn("wireLatestButton", room_js)
        self.assertIn("room-latest", room_js)
        self.assertIn('roomInput.addEventListener("keydown"', room_js)
        self.assertIn('e.key !== "Enter"', room_js)
        self.assertIn("e.shiftKey", room_js)
        self.assertIn("e.isComposing", room_js)
        self.assertIn("e.keyCode === 229", room_js)
        self.assertIn("roomForm.requestSubmit", room_js)
        self.assertIn("rapid_input", room_js)
        self.assertIn("미처리 입력", room_js)
        self.assertIn("pending_input_count", room_js)
        self.assertIn("unread_event_count", room_js)
        self.assertIn('chips.unshift(["outbox"', room_js)
        self.assertIn('chips.push(["backlog"', room_js)
        self.assertIn(".snapshot-chip.outbox", css)
        self.assertIn(".snapshot-chip.backlog", css)
        self.assertIn(".msg.outbox", css)
        self.assertIn(".status-detail-row.backlog", css)
        self.assertIn(".msg-meta.error", css)
        self.assertNotIn("let sending", room_js)
        self.assertNotIn("if (!currentSpace || sending) return", room_js)
        self.assertNotIn("submit.disabled = true", room_js)
        self.assertNotIn("전송 API는 성공했을 수 있습니다", room_js)
        self.assertNotIn("`idx:${index}`", room_js)

    def test_cli_chat_default_uses_space_manager_policy(self):
        world_py = (ROOT / "시스템/엔진/world.py").read_text(encoding="utf-8")
        engine_py = (ROOT / "시스템/core/engine.py").read_text(encoding="utf-8")
        router_py = (ROOT / "시스템/대시보드/서버/routers/spaces.py").read_text(encoding="utf-8")

        self.assertIn("chat_policy.should_run_space_manager", world_py)
        self.assertIn("--direct-diagnostic", world_py)
        self.assertIn("direct_diagnostic=True", world_py)
        self.assertIn("room_manager.post(", engine_py)
        self.assertIn('"managed_by": "space_manager"', engine_py)
        self.assertIn("direct diagnostic chat cannot write transcript", engine_py)
        self.assertIn("chat_policy.should_run_space_manager", router_py)
        self.assertNotIn("print(engine.chat(x.person, x.space, x.text, x.requester, x.engine, x.model))", world_py)

    def test_mobile_snapshot_has_height_guard(self):
        css = (ROOT / "시스템/대시보드/웹/css/style.css").read_text(encoding="utf-8")
        self.assertIn("@media (max-width: 720px)", css)
        self.assertIn(".room-snapshot { max-height: 56px;", css)
        self.assertIn(".room-diagnostics-toolbar", css)
        self.assertIn(".observer-section-toggles", css)
        self.assertIn(".observer-toggle", css)
        self.assertIn(".layout-panel", css)
        self.assertIn(".people-pane", css)
        self.assertIn(".spaces-pane", css)
        self.assertIn(".chat-pane", css)
        self.assertIn(".viewer-pane", css)
        self.assertIn(".workspace-splitter", css)
        self.assertIn(".workspace-splitter[data-hidden=\"yes\"]", css)
        self.assertIn("body.layout-resizing", css)
        self.assertIn("body.layout-resizing iframe", css)
        self.assertIn("body.panel-agents-collapsed .people-pane", css)
        self.assertIn("body.panel-spaces-collapsed .spaces-pane", css)
        self.assertIn("body.panel-chat-collapsed .chat-pane", css)
        self.assertIn("body.panel-viewer-collapsed .viewer-pane", css)
        self.assertIn("grid-template-columns:", css)
        self.assertIn(".room-view", css)
        self.assertIn("height: min(var(--m-h-chat, 88dvh), calc(100dvh - 8px));", css)
        self.assertIn("min-height: min(420px, calc(100dvh - 8px));", css)
        self.assertIn("grid-template-columns: auto minmax(0, 1fr) auto auto;", css)
        self.assertIn(".room-observer-stack { max-height: min(16dvh, 128px);", css)
        self.assertIn(".room-latest-btn", css)
        self.assertNotIn(".chat-pane:has(#room-monitor:not([hidden])) { height: auto; }", css)
        self.assertIn("#roomView[data-observer-collapsed=\"yes\"] .room-snapshot", css)
        self.assertIn("#roomView [data-section-hidden=\"yes\"]", css)
        self.assertIn(".snapshot-chip.generation", css)
        self.assertIn(".snapshot-chip.intent", css)
        self.assertIn(".snapshot-chip.publish", css)
        self.assertIn(".snapshot-chip.pack", css)
        self.assertIn(".snapshot-chip.memory", css)
        self.assertIn(".snapshot-chip.handoff", css)
        self.assertIn(".snapshot-chip.lessonpack", css)
        self.assertIn(".snapshot-chip.tasks", css)
        self.assertIn(".sub.work-settings", css)
        self.assertIn(".seat-settings-panel", css)
        self.assertIn(".seat-settings-count", css)
        self.assertIn(".seat-actions", css)
        self.assertIn(".seat-work-settings-btn", css)
        self.assertIn("max-height: 150px", css)
        self.assertIn("max-height: 120px", css)
        self.assertIn(".work-settings-note", css)
        self.assertIn(".work-override-row", css)
        self.assertIn(".room-manager-lock", css)
        self.assertIn(".msg.transient", css)
        self.assertIn(".snapshot-chip.release", css)
        self.assertIn(".snapshot-chip.candidate", css)
        self.assertIn(".snapshot-chip.learning", css)
        self.assertIn(".snapshot-chip.baseline", css)
        self.assertIn(".room-status-detail", css)
        self.assertIn(".room-observer-stack", css)
        self.assertIn(".chat-flow-panel", css)
        self.assertIn(".chat-flow-list", css)
        self.assertIn(".chat-flow-step.current", css)
        self.assertIn(".chat-flow-blockers", css)
        self.assertIn(".turn-handoff-panel", css)
        self.assertIn(".turn-handoff-panel[data-empty=\"yes\"]", css)
        self.assertIn(".turn-handoff-grid", css)
        self.assertIn(".turn-handoff-brief", css)
        self.assertIn("overflow-wrap: anywhere", css)
        self.assertIn(".status-detail-row.failure", css)
        self.assertIn(".status-detail-row.recovery", css)
        self.assertIn(".status-detail-row.task-runtime", css)
        self.assertIn(".status-detail-row.cancel", css)
        self.assertIn(".status-detail-row.candidate", css)
        self.assertIn(".status-detail-row.memory", css)
        self.assertIn(".status-detail-row.baseline", css)
        self.assertIn(".obligation-row.overdue", css)
        self.assertIn(".status-actions", css)
        self.assertIn(".status-action", css)
        self.assertIn(".task-panel", css)
        self.assertIn(".task-list", css)
        self.assertIn(".task-row.stale", css)
        self.assertIn(".task-count.stale", css)
        self.assertIn(".task-actions", css)
        self.assertIn(".task-action", css)
        self.assertIn(".task-control-modal textarea", css)
        self.assertIn(".task-note.steering-note", css)
        self.assertIn(".candidate-panel", css)
        self.assertIn(".candidate-list", css)
        self.assertIn(".candidate-row.selected", css)
        self.assertIn(".candidate-row.synthesized", css)
        self.assertIn(".candidate-row.superseded", css)
        self.assertIn(".promotion-review-panel", css)
        self.assertIn(".promotion-review-panel[data-empty=\"yes\"]", css)
        self.assertIn(".promotion-review-list", css)
        self.assertIn(".promotion-review-row.pending", css)
        self.assertIn(".promotion-review-row.apply-pending", css)
        self.assertIn(".promotion-review-row.apply-applied", css)
        self.assertIn(".promotion-review-row.apply-blocked", css)
        self.assertIn(".promotion-review-action", css)
        self.assertIn(".promotion-review-action.scan", css)
        self.assertIn(".promotion-review-action.apply", css)
        self.assertIn("max-height: 96px", css)
        self.assertIn("max-height: min(16dvh, 128px)", css)
        self.assertIn("max-height: min(36dvh, 360px)", css)
        self.assertIn("max-height: 132px", css)
        self.assertIn("max-height: 132px", css)
        self.assertIn("max-height: 72px", css)
        self.assertIn("max-height: 56px", css)
        self.assertIn("max-height: 72px", css)
        self.assertIn("flex-wrap: nowrap", css)
        self.assertIn(".task-top { flex-wrap: wrap;", css)
        self.assertIn(".task-top strong { flex: 1 1 120px;", css)
        self.assertIn(".task-action { min-height: 38px;", css)
        self.assertIn(".room-activity { max-height: 64px;", css)
        self.assertIn(".activity-toolbar", css)
        self.assertIn(".activity-filter", css)
        self.assertIn(".activity-filter[aria-pressed=\"true\"]", css)
        self.assertIn(".activity-list", css)
        self.assertIn("-webkit-line-clamp: 2", css)

    def test_static_cache_versions_and_release_api_paths_are_consistent(self):
        index = (ROOT / "시스템/대시보드/웹/index.html").read_text(encoding="utf-8")
        js_dir = ROOT / "시스템/대시보드/웹/js"
        js_text = "\n".join(path.read_text(encoding="utf-8") for path in sorted(js_dir.glob("*.js")))
        viewer = (js_dir / "viewer.js").read_text(encoding="utf-8")
        room = (js_dir / "room-chat.js").read_text(encoding="utf-8")
        api = (ROOT / "시스템/대시보드/웹/js/api.js").read_text(encoding="utf-8")
        css = (ROOT / "시스템/대시보드/웹/css/style.css").read_text(encoding="utf-8")
        # 캐시버전 컨벤션은 YYYYMMDD-NN (8자리 날짜 + 2~4자리 일련번호). 모든 곳이 한 값으로 일치해야 한다.
        versions = set(re.findall(r"v=(\d{8}-\d{2,4})", index + js_text))
        versionless_imports = [
            line for line in js_text.splitlines()
            if line.startswith("import ") and "./" in line and "?v=" not in line
        ]

        self.assertEqual(len(versions), 1)
        self.assertEqual(versionless_imports, [])
        self.assertIn("room-task-panel", index)
        self.assertIn("room-turn-handoff", index)
        self.assertIn("room-candidate-panel", index)
        self.assertIn("room-promotion-review", index)
        self.assertIn("room-diagnostics-toolbar", index)
        self.assertIn("LAYOUT_STORAGE_KEY", viewer)
        self.assertIn("LAYOUT_WIDTH_STORAGE_KEY", viewer)
        self.assertIn('const SPLITTER_WIDTH = "10px"', viewer)
        self.assertIn("nextVisibleByLeft", viewer)
        self.assertIn("dataset.homeLeft", viewer)
        self.assertIn("패널 ${axis} 조절", viewer)
        self.assertIn("setLayoutPanelCollapsed", viewer)
        self.assertIn("startSplitterDrag", viewer)
        self.assertIn("resizePanelPair", viewer)
        self.assertIn("savePanelFractions", viewer)
        self.assertIn("setPointerCapture", viewer)
        self.assertIn("ArrowLeft", viewer)
        self.assertIn("ArrowRight", viewer)
        self.assertIn("workspace.style.gridTemplateColumns", viewer)
        self.assertIn("width: 10px; min-width: 10px", css)
        self.assertIn("linear-gradient(90deg, #090d14", css)
        self.assertIn("deletePerson", api)
        self.assertIn("deleteSpace", api)
        self.assertIn('method: "DELETE"', api)
        self.assertIn("person-delete-btn", js_text)
        self.assertIn("space-delete-btn", js_text)
        self.assertIn("openPersonPickerModal", js_text)
        self.assertIn("room-member-form", js_text)
        self.assertIn("refreshRoomSpaceSelect", js_text)
        self.assertIn("room-space-select", room)
        self.assertIn("renderRoomSpaceSelect", room)
        self.assertIn("spaceOptionLabel", room)
        self.assertIn("공간 선택", room)
        self.assertIn("await openSpaceChat(space)", room)
        self.assertIn("room-space-control", css)
        self.assertIn("refreshCurrentRoomParticipants", js_text)
        self.assertIn("room-participants", room)
        self.assertIn("renderRoomParticipants", room)
        self.assertIn("refreshRoomParticipants", room)
        self.assertIn("api.spaces()", room)
        self.assertIn("참여 ${members.length}명", room)
        self.assertIn("참여 에이전트 없음", room)
        self.assertIn(".room-participant-chip", css)
        self.assertIn("clearSpaceChatIfCurrent", js_text)
        self.assertIn("FILE_SPLIT_STORAGE_KEY", js_text)
        self.assertIn("startFilesSplitDrag", js_text)
        self.assertIn("files-splitter", js_text)
        self.assertIn('setLayoutPanelCollapsed("chat", false)', room)
        self.assertIn('document.getElementById("chat-panel").scrollIntoView', room)
        self.assertIn("/releases/${encodeURIComponent(releaseId)}/approve", api)
        self.assertIn("/releases/${encodeURIComponent(releaseId)}/reject", api)
        self.assertIn("/releases/${encodeURIComponent(releaseId)}/publish", api)
        self.assertIn("/tasks/${encodeURIComponent(taskId)}/cancel", api)
        self.assertIn("/tasks/${encodeURIComponent(taskId)}/progress", api)
        self.assertIn("/tasks/${encodeURIComponent(taskId)}/revise", api)
        self.assertIn("/tasks/${encodeURIComponent(taskId)}/work-settings", api)
        self.assertIn("/learning/promotions/scan", api)
        self.assertIn("/learning/promotions/${encodeURIComponent(promotionId)}/approve", api)
        self.assertIn("/learning/promotions/${encodeURIComponent(promotionId)}/reject", api)
        self.assertIn("/learning/promotions/${encodeURIComponent(promotionId)}/apply", api)
        self.assertIn("/members/${encodeURIComponent(person)}/work-settings", api)
        self.assertIn("/activity?limit=", api)
        self.assertIn("/work-settings", api)
        self.assertIn("candidate_queue", room)
        self.assertIn("pendingCandidates", room)
        self.assertIn("Promise.all", room)
        self.assertIn("reasonInput === null", room)
        self.assertIn("api.cancelTask", room)
        self.assertIn("api.progressTask", room)
        self.assertIn("api.reviseTask", room)
        self.assertIn("api.scanLessonPromotions", room)
        self.assertIn("api.approveLessonPromotion", room)
        self.assertIn("api.rejectLessonPromotion", room)


if __name__ == "__main__":
    unittest.main()
